export const routePaths = {
  login: '/login',
  dashboard: '/dashboard',
  products: '/products',
  productsNew: '/products/new',
  productsEdit: '/products/:id',
  orders: '/orders',
  ordersDetail: '/orders/:id',
  inventory: '/inventory',
  purchaseOrders: '/purchase-orders',
  units: '/units',
  coupons: '/coupons',
  layout: '/layout',
  layoutHome: '/layout/homepage',
  layoutShop: '/layout/shop',
  settings: '/settings',
  users: '/settings/users',
  roles: '/settings/roles',
} as const
